[build]
    functions = "functions"

[[redirects]] 
    from = "/*" 
    to = "/.netlify/functions/app/:splat" 
    status = 200 
    force = true

[functions]
    included_files = ["src/Config/MongoDB/Models/PemFiles/cert.pem", "src/Config/MongoDB/Models/PemFiles/key.pem"]