[build]
    functions = "functions"

[[redirects]]
    from = "/socket.io/*"
    to = "/.netlify/functions/api"
    status = 200
    force = true

[[redirects]] 
    from = "/*" 
    to = "/.netlify/functions/app/:splat" 
    status = 200 
    force = true


[functions]
    included_files = ["src/index.html", "src/PEM/cert.pem", "src/PEM/key.pem"]